### ISSUE TITLE
[BUDI-6820] App icons and colors get lost after container updates

### ISSUE THREAD

**Issue by dewdeded** [Budibase/budibase#10189]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: Docker Compose (budi cli tool)
  - Budibase Version: 2.4.43 
  - App Version: 2.4.43
  - Host: Ubuntu 20.04.1 LTS

**Describe the bug**
After every update, done via budi-CLI tool all our apps lose their app icon and app color.
Problem exists since over a year at least, it's annoying. These colors and icons help to organize the apps and the users to identify the app they need/want/have to use, after logging in the BB portal.

**To Reproduce**
1. Assign icon and color to app
2. Execute update of the docker containers via budi CLI tool (budi hosting --update)
3. See the effect, that these attributes of the app are gone

**Expected behavior**
App color and icon stays the same as configured and desired.

**Screenshots**
![missing_app_icons_and_colors](https://user-images.githubusercontent.com/7132234/229327050-54586c55-bd0c-4f87-aa99-39e5bd21f00b.png)

**Desktop:**
 - OS: Mac OS X
 - Browser Firefox 111.0.1 & Safari 16.4

<sub>[BUDI-6820](https://linear.app/budibase/issue/BUDI-6820/app-icons-and-colors-get-lost-after-container-updates)</sub>

**Comment by andz-bb** [comment]
Could not recreate with a self host single image instance running on 2.4.x, running `budi hosting --update`  and then checking on  2.5.2. 

![image.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/aaf6b0cf-46f8-4ee1-a4e1-41c22f858d6c/3c262bcc-6da1-4383-9a24-f16288387a06)

![Screenshot 2023-04-11 at 14.11.00.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/94a0d4a5-8fd3-4ba5-bebb-cd627cce37c5/19b34bf6-66c2-43fe-8016-aff0c8b6ae60)

![image.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/60e1c5e4-9cc2-403b-b321-740d64c0cba4/942ecaa0-0edd-43bc-ae81-14016205bd6c)

As a side note when I tried to change the icon of apps that had already been published with the default icon, the icon change was getting lost when I published those apps again.

**Comment by dewdeded** [comment]
This is still happends. Also we lose the favicon setting under branding every 6 hours.

Where are these infos (icon colors) and the file (favicon) stored, so I can investigate.

**Comment by dewdeded** [comment]
I found the fav-icon storage location.

It is in the budi_minio_data volume in the folder /_data/global/settings.

**Comment by melohagan** [comment]
Could not reproduce. Appears to be fixed.
