### ISSUE TITLE
Unable to update Organisation logo

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#2388]
**Describe the bug**
Just installed BB on a new clean server. App is imported correctly. 
Organisation logo update (user logo) does not work. Always previous one is shown.

**To Reproduce**
1. Go to 'Builder>settings>Organisation'
2. Click on 'Logo>Select a file to upload'
3. Logo showed in the form once uploaded
4. Click Save button
5. Check that logo was not saved & updated, and previous one (BB logo in my case) is sill shown.

**Expected behavior**
Previous logo should be replaced by user uploaded one

I used the same svg file (logo) as I used all the time in bb.
v0.9.107

**Comment by sergey-dme** [comment]
The issue is present in v0.9.105 too.

**Comment by PClmnt** [comment]
Hey Sergey, I was able to reproduce this on my machine. Currently having a look into why it's happening.

**Comment by sergey-dme** [comment]
Hey @PClmnt Thanks for responding. Other form filed work as before, Org name and Platform URL can be stored/saved, the problem only with the attachment.

**Comment by brunnobb** [comment]
Confirmed here too

**Comment by PClmnt** [comment]
This should be fixed now @sergey-dme @brunnobb. Let me know if there are any further issues.

**Comment by sergey-dme** [comment]
Hey @PClmnt just tried `hosting --update` but seems it's not yet available. Anyway thanks for quickly fixing this!

**Comment by brunnobb** [comment]
Thanks. I'll try later today and ping back

**Comment by sergey-dme** [comment]
Hi @PClmnt just updated to v0.9.108 the issue is still present

**Comment by PClmnt** [comment]
Hey Sergey, can you try now? You may need to clear your cache.

**Comment by sergey-dme** [comment]
Hey @PClmnt It works now! Thanks a lot!
