### ISSUE TITLE
Document update conflict - Saving Relational Data - >8 Child Rows

### ISSUE THREAD

**Issue by conorw** [Budibase/budibase#5075]
**Describe the bug**
When I try to save particular records, either through the admin UI or an edit UI, I receive the following http Error:

{"message":"Document update conflict.","status":400}

It would apprear that it starts to occur when trying to save a parent record with >8 child relationship rows.

![image](https://user-images.githubusercontent.com/3536589/159920186-d16488a7-9326-46e1-8f3d-a13f86086bf3.png)

**To Reproduce**
1. Create a parent table (e.g. "Person") with >10 columns
2. Create a child table (e.g. "Attendance") with >10 columns
3. Add a parent child relationship between the tables
4. Add 10x child rows for the parent
5. Open the parent record and try to save.
6. This bug may be dependent on the amount of child rows in the database. I can currently create with a table of ~1000 child rows.
Also, when the save is unsuccessful, duplicate records are created in the database:

![image](https://user-images.githubusercontent.com/3536589/159934090-aeb48753-a5e8-4f54-8595-662e5fd8a91c.png)

**Expected behavior**
The parent record should save

**Screenshots**

**Desktop (please complete the following information):**
Windows, Chrome (Latest)

**Additional context**
Both the parent and child have static calculated fields, I'm not sure if this affects anything.
Also, This bug may be dependent on the number of child rows in the database. I can currently create with a table of ~1000 child rows.

**Comment by sangroxx** [comment]
Getting the same error

![image](https://user-images.githubusercontent.com/10852022/160236999-88ff438c-0ad5-4e01-a921-4864a56b8166.png)

Is this a CouchDB Limitation

**Comment by conorw** [comment]
@shogunpurple unfortunately this issue has rendered our current app unusable for the time-being.
I would be able to help out with this issue but I currently cannot run the dev code (windows machine).

**Comment by shogunpurple** [comment]
Hi @conorw - sorry to hear that. We will get this one addressed ASAP. Thanks!

**Comment by shogunpurple** [comment]
@conorw - would you be able to share your database schema here too so that I can recreate on my local env? Thanks

**Comment by conorw** [comment]
thanks @shogunpurple, is there a quick way to export this from BB (all the tables are BB internal tables)?

**Comment by conorw** [comment]
> thanks @shogunpurple, is there a quick way to export this from BB (all the tables are BB internal tables)? 

I can create an empty export, if that helps?

**Comment by shogunpurple** [comment]
@conorw that would be helpful, thanks!

**Comment by conorw** [comment]
@shogunpurple unfortunately, after deleting all the data in the database, the export is still 12mb (as it exports all the deleted entries too).

However, here is a very quick video outlining the issue (which may or may not be related to the large amount of records, albeit deleted, in the database):

https://crvideos.bonjoro.com/r/25ba4d35-ae1c-4003-8e37-3c1f0ecd1501

**Comment by conorw** [comment]
@shogunpurple not sure what happened, but in the example app shown in the video above, the save now completes successfully.
I tried to export this app again and it is now only 16kb (as opposed to 10mb previously, mostly made up of _deleted records).

Is there some kind of automated purge of _deleted documents from the couchdb or is it a manual process?

If its manual, could you try to purge the following tables? ta_71acec41838e4ecb81a6482ee8d82424 ta_71acec41838e4ecb81a6482ee8d82424

**Comment by shogunpurple** [comment]
Hi @conorw - we just rolled out the latest release of budibase this morning, so it appears this is either a bug that may have been fixed, or it was in fact the old `_deleted` documents being held around. There is an automated "purge" that happens called compaction (https://docs.couchdb.org/en/3.2.0/maintenance/compaction.html) 

I can however trigger a manual compaction on your database if you tell me your app ID, and I'll run it and see if that helps.

**Comment by conorw** [comment]
super, thanks @shogunpurple, running a compaction would be great, the appid is app_dev_solas_b8609a028a8442fbbb2e6d0b33d12efb

**Comment by shogunpurple** [comment]
Thanks @conorw - that's compacted now.

**Comment by conorw** [comment]
thanks @shogunpurple. 
unfortunately, it looks to have had no effect on this database, it is still the same size (10mb) and contains ~4000 deleted records:
"_deleted":true

Not sure if its related but quite a few of the _deleted records are 'sample' records from tables that no longer exist, e.g. 
"tableId":"ta_1c2dbd96e17c430e8b0cd27f0decb692","Auto ID":134,"Created At":"2021-12-13T17:32:02.171Z","Updated At":"2021-12-13T17:32:02.171Z","_deleted":true,"_revisions":{"start":2,"ids":["240fda8f077a6959e095b075e35d166d","77532cd0d38a26f64a65eb6ff115e178"]}},{"_id":"ro_ta_1c2dbd96e17c430e8b0cd27f0decb692_0138453a6b184d3bb14e1799e273652c","_rev":"2-058667f8f5a104504c299393a9c57f3f","id":"34","first_name":"Basilius","last_name":"Domke","gender":"Male","grade":"9","attendance_(%)":60,"tardiness_(days)":48,"home_number":"863-952-3812","tableId":"ta_1c2dbd96e17c430e8b0cd27f0decb692","Auto ID":34,"Created At":"2021-12-13T17:32:02.143Z","Updated At":"2021-12-13T17:32:02.143Z","_deleted":true,"_revisions":{"start":2,"ids":["058667f8f5a104504c299393a9c57f3f","d7152cfd743af0226b588cfdec3326c0"]}},{"_id":"ro_ta_1c2dbd96e17c430e8b0cd27f0decb692_01c0b3763a0d4ef491dd0b4ac3f3c8db","_rev":"2-8965f27d028cba8ddddafdebf6cbe079","id":"153","first_name":"Philly","last_name":"McNea","gender":"Female","grade":"9","attendance_(%)":7,"tardiness_(days)":66,"home_number":"433-199-6578","tableId":"ta_1c2dbd96e17c430e8b0cd27f0decb692","Auto ID":153,"Created At":"2021-12-13T17:32:02.174Z","Updated At":"2021-12-13T17:32:02.174Z","_deleted":true,"_revisions":{"start":2,"ids":["8965f27d028cba8ddddafdebf6cbe079","7fcbdf692bd59318c75781e72fc1eb6f"]}},

**Comment by conorw** [comment]
sorry to bother again @shogunpurple, but is there any way for me to remove the _deleted records from the database?
Unfortunately we still cannot use the app due to document conflicts.

**Comment by shogunpurple** [comment]
Hey @conorw - so I've been looking into this and I'm thinking that it's something to do with bulk deletion, which makes use of the `_deleted` field. 

According to couch - the only way to update this is to manually purge all the old records and their individual document IDs, then compact. Now, I can do this - I just need to write a script to do it. 

But what I am not understanding is how it's causing conflicts - is it possible that you deleted a document that was part of a relationship. Before your reproduction steps, had you been deleting documents regularly? Just trying to understand root cause here.

**Comment by conorw** [comment]
@shogunpurple I could very well have unintentionally deleted a record that was part of a relationship, but I'm not sure.

Previously, I would have "cleared" both tables at least twice (each around ~500 rows) by individually selecting each row in the admin UI and deleting.

To re-populate the child table I then used Postman to read a CSV file and bulk insert the relational records (see below)

![image](https://user-images.githubusercontent.com/3536589/162184884-4f9b86d9-78ea-49e2-ac20-e151d7b60ae3.png)

**Comment by shogunpurple** [comment]
Ok thanks @conorw - so this is almost certain to be the issue. I did not realise that you were manually creating relationships through the undocumented, deprecated API. It seems like the relationship data has been corrupted in some way.

I'm not sure where to go from here to debug this issue now - the manual creation of relationship rows is not a supported setup in budibase. If you could provide a full app export, we could look into this and the team can debug, but an empty one is not useful. Is that something you would be willing to provide, or is there a way to recreate this from a fresh app?

**Comment by conorw** [comment]
@shogunpurple i'm having a "related" issue with relational data (pun intended :) ) here: https://github.com/Budibase/budibase/discussions/5299

I might just denormalize the data and hopefully this should address both issues i.e.
- Add formulas to the existing tables to extract the id and name of the child relation
- Export the table data to CSV
- Create a new table without the relational fields.
- Import the CSV data into the table
- Update the app screens to use the new tables 
- Delete the old relational tables

Do you think this would work, or am I opening myself up to other issues?

**Comment by shogunpurple** [comment]
Hey @conorw - when using the internal budibase DB, it is always much more performant and easier to manage when you denormalise everything as it's built on NoSQL. I would try what you have suggested - I think you will end up with a much better app as a result. You can make use of the JSON column for nested data, and by using wider tables, it's going to be much easier to manage and query.

If your data is highly relational, you are better off using one of our SQL integrations and auto generation features.

**Comment by conorw** [comment]
thanks @shogunpurple, good call on the json datatype, didnt think of that

**Comment by JCV67** [comment]
Hello, 
I'm having the same problem (Document update conflict), but my tables are internal. I have one main table where two of the columns are relationships (many to many)  to two other tables. In the main table I use (static) formula to extract single columns from the relationship columns. Deleted all data and tested again but the problem persists. My Budibase system is self hosted and the version is 1.2.36  Could you help me?  Thank you

**Comment by nschaeff2000** [comment]
Hello
I got the same "Document update conflict." issue on Users internal table, but with no relationship at All : 
Got Self hosted v 2.0.3 through Docker Compose
Create a App from scratch : no table, no data
Add a single user to the App
Create a Column in Users internal table (eg: "Entity", text, not required)
Try to Edit the user row, fill in the 'Entity" field -> Click "Save User" -> got "Document update conflict."
Regards
<img width="938" alt="Budi 01" src="https://user-images.githubusercontent.com/64425181/192959573-1e5015dc-b421-4b3c-9e7b-1b1956628dd4.PNG">
<img width="266" alt="Budi 02" src="https://user-images.githubusercontent.com/64425181/192959592-a08c19f5-437c-45d9-8753-db5740f1cf1d.PNG">
