### ISSUE TITLE
The attachment name should be the same both when uploaded and downloaded

### ISSUE THREAD

**Issue by Klience** [Budibase/budibase#7257]
**Describe the feature request**
The attachment name should be the same both when uploaded and downloaded.

Right now if we upload an attachment named e.g. "**Sales Agreement.docx**" it shows it's correct name inside the "Attachment" form element (sales agreement.docx).

But when clicked on that name to download, the name of the downloaded file is the internal id of that attachment, e.g. "**c73cc0bf-8610-4075-9fa3-ae9d34037ab5.docx**"

That way we have to rename it manually ourselves when downloading attachments.

**Comment by aptkingston** [comment]
Great suggestion! Just leaving this here for reference, but in order to support this we would need to proxy attachment downloads through the server, so that we can internally fetch the file, then rename it and push it to the client. Proxying all attachments through the server could lead to a fair bit more load, especially for large attachments.

The better choice would be storing attachments in more uniquely named buckets so that we could just use their original file names. Including the row ID in the name of the bucket would not only let us use the original names, but also let us do things like cleaning up attachments when rows are deleted much easier.

**Comment by aderici** [comment]
@aptkingston is this an option? For the frontend : 

```
<a href="path/to/file" download="renamed.txt">Download</a>
<a href="downloads/export.xlsx" download="Data-Export.xlsx">Download Export</a>
```

**Comment by aptkingston** [comment]
> @aptkingston is this an option? For the frontend :
> 
> ```
> <a href="path/to/file" download="renamed.txt">Download</a>
> <a href="downloads/export.xlsx" download="Data-Export.xlsx">Download Export</a>
> ```

You learn something new every day! I had no idea that the `download` attribute can rename files. This would be perfect :+1:

**Comment by Klience** [comment]
Noticed that #7270 was pushed to master. Does that mean the problem was fixed?

I updated the cloud Budibase app to 1.2.43, but the files still have internal IDs when downloaded.

**Comment by aptkingston** [comment]
It's in master but we just haven't deployed it yet, but it should go out soon!

**Comment by Klience** [comment]
Thanks for the heads up. I'm not a developer, so I'm not familiar with how you deploy things.

Thanks for the clarification once again!

**Comment by aptkingston** [comment]
This has been deployed now, although I've just realised that the problem is only fixed for self-host, but not for our cloud. I hadn't realised that the `download` attribute only works for URLs in the same origin, and because we use a different domain for attachments in our cloud, the issue has not been fixed there. 

So it's fixed in self-host but not fixed in cloud. We'll have to come up with some other solution for cloud.
