### ISSUE TITLE
multi-select for bulk actions improvement

### ISSUE THREAD

**Issue by samg666** [Budibase/budibase#7645]
Hello,

As the multi-select is very useful feature and used quite often, currently the multi-select feature can be achieve by below methods:

1. Use the table component and enable the `Allow row selection`, then get the `{{ Table.Selected rows }}` for bulck actions. But this feature only work for tables, but not work for custom queries. 
2. Use the repeater and checkbox component, then add the `On Change` with some custom Javascript code on the checkbox, store the `selected row ids` to the `App State`. This way actually works for me, but the only issue is the `checkbox` actions always response very slow(I have raised issue #6548) which makes the user experience very bad.  

Beside above two method, is there any other way to achieve multi-select bulk actions? Or is there any way to improve the checkbox action response?

**Comment by pandel** [comment]
I second this!

My JS code for the checkbox looks like this:
```
let a=$("State.ROW_SELECT");
if (Array.isArray(a)) {
	if ($("Field Value") == true) {
		a.push($("Repeater.Source Table.id"));
		return a;
	} else {
		var index = a.indexOf($("Repeater.Source Table.id")); 
		if (index !== -1){
			a.splice(index, 1);
			return a;
		}
	}
} else {
	if ($("Field Value") == true) {
		return [$("Repeater.Repeater.Source Table.id")];
	} else {
		return [];
	}
}
```

Later on I am using this inside an automation loop.

But somehow, since I upgraded to 1.3.1 and then [downgraded](https://github.com/Budibase/budibase/issues/7630) again to 1.2.58, because my design view was broken, the script does not work as before. If click a checkbox, the desired value gets added to the array, but then no other, additional one if I click another checkbox. It worked for quite some time now, but not atm.

This checkbox+repeater thing really seems to be in need of some attendance.

Regards,
Holger

**Comment by JayP718** [comment]
@samg666 

I created a feature requests which allows custom queries to be used for tables. Feel free to upvote if you feel it would help with your use case as well.

https://github.com/Budibase/budibase/issues/7348

**Comment by pandel** [comment]
FYI, for me, problems are solved, I'll keep using the JS method. It had to do with the structure of the component tree, see https://github.com/Budibase/budibase/issues/7668#issuecomment-1239319353

**Comment by samg666** [comment]
> 

@pandel Thank you very much for your help. I have tried your way, put a Form2 inside the repeater then put checkbox inside the Form2, then use the JS code you have provided, the multi-select works just fine, but still the same problem as my way, when click the checkbox it's response lagging. 

# checkbox inside the Form2, and Form2 inside the repeater
<img width="411" alt="image" src="https://user-images.githubusercontent.com/29649651/188920911-99a19979-5baf-4df6-9ec2-629a9d4e44cc.png">

# Click response lagging
![iShot_2022-09-07_23 39 43](https://user-images.githubusercontent.com/29649651/188921511-11c1a2fa-1426-4c8e-a8e7-32a43a65e150.gif)

**Comment by pandel** [comment]
@samg666 
My checkboxes are a very little bit laggy too, but I am fine with it. Perhaps it has something to do with how many rows your data provider is giving you. I read somewhere that changes to an app state variable results in a more complex page update in the background. Perhaps it is simply the amount of components you're page is made of...

**Comment by Rory-Powell** [comment]
Dupe of: https://github.com/Budibase/budibase/issues/7348
